### ISSUE TITLE
关于潜在的XSS问题

### ISSUE THREAD

**Issue by lakejason0** [hiugiak/cj-typo#20]
我正在寻找网页标点挤压的实现方案，于是找到了这个项目。

我在使用的时候发现，单独的一个`<p>`包裹已经被转义掉的`<script>`或`<summary>`，会导致该标签取消转义，进入DOM，但不知为何在我的网页上转义后的`<script>`标签在启用该脚本后进入了DOM但并没有执行。

**Comment by hiugiak** [comment]
> 我正在寻找网页标点挤压的实现方案，于是找到了这个项目。
> 
> 我在使用的时候发现，单独的一个`<p>`包裹已经被转义掉的`<script>`或`<summary>`，会导致该标签取消转义，进入DOM，但不知为何在我的网页上转义后的`<script>`标签在启用该脚本后进入了DOM但并没有执行。

来段html代码看看？

**Comment by lakejason0** [comment]
> > 我正在寻找网页标点挤压的实现方案，于是找到了这个项目。
> > 
> > 我在使用的时候发现，单独的一个`<p>`包裹已经被转义掉的`<script>`或`<summary>`，会导致该标签取消转义，进入DOM，但不知为何在我的网页上转义后的`<script>`标签在启用该脚本后进入了DOM但并没有执行。
> 
> 来段html代码看看？

讲实话我不太清楚怎么提供（因为我是MediaWiki）。你可以注册并登录我的网站 [存档](https://lakeus.xyz/)，然后在参数设置的小工具内打开CJ Typographer。

**Comment by hiugiak** [comment]
@lakejason0 这个PR #21 应该已经修复这个问题了，不妨再试试

**Comment by lakejason0** [comment]
了解。由于评论时手头没有构建条件，稍后尝试构建并应用。

**Comment by lakejason0** [comment]
> @lakejason0 这个PR #21 应该已经修复这个问题了，不妨再试试

已修复。还有一些规则上的疑问我会放在另一个issue里面。
